sonar.projectKey=omrl_prova01-unit-test-MuriloSalvan
sonar.organization=omrl
sonar.projectName=Jest Unit Tests
sonar.projectVersion=1.0
sonar.sources=./src
sonar.tests=./test
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=./coverage/lcov.info